sequenceDiagram
    autonumber
    Client 💻->>+Serveur 💽: Requête: https://www.google.com
    Serveur 💽->>+Serveur 💽: Traitement...
    Serveur 💽-->>-Client 💻: Réponse: <html>...</html>
    Client 💻->>+Client 💻: Affiche résultat