sequenceDiagram
    autonumber
    box Frontend
    participant Client
    end
    box Backend
    participant Serveur
    participant BDD
    end
    Note over BDD: Base de données (BDD)
    Client->>+Serveur: Requête: https://www.google.com
    Serveur->>+Serveur: Traitement: validation...
    Serveur->>+BDD: Requête: récupère liste résulats
    BDD-->>-Serveur: Réponse: [resulat 1, resultat 2,...]
    Serveur->>+Serveur: Construction page
    Serveur-->>-Client: Réponse: <html>...</html>
    Client->>+Client: Affiche résultat